### PR TITLE
Add chr21 version of bed file for NGSCheckMate

### PR DESCRIPTION
**Pull request by SPPearce**
Add chr21 version of bed file for NGSCheckMate

### CODE REVIEW

**Review by maxulysse — APPROVED** [review]

**Comment by SPPearce** [comment]
> this file is in the modules branch too?

Not yet, shall I make the same PR against the modules branch too?

**Comment by maxulysse** [comment]
> > this file is in the modules branch too?
> 
> Not yet, shall I make the same PR against the modules branch too?

I'd say this branch is too different from modules, it won't work

**Comment by maxulysse** [comment]
Can you update this file as well:
https://github.com/nf-core/test-datasets/blob/sarek3/get_files.sh

**Comment by SPPearce** [comment]
> > > this file is in the modules branch too?
> > 
> > Not yet, shall I make the same PR against the modules branch too?
> 
> I'd say this branch is too different from modules, it won't work

Sure, I'll make a new PR with the same change

**Comment by SPPearce** [comment]
@maxulysse , I've also opened a PR to add to modules: https://github.com/nf-core/test-datasets/pull/1017

**Review by maxulysse — APPROVED** [review]

**Pull request merged**
