### PR TITLE
Add new simulated sv vcf files

### PR DESCRIPTION
**Pull request by nvnieuwk**

### CODE REVIEW

**Comment by FriederikeHanssen** [comment]
looks good. Cn you update the readmes? The one where all files are listed and the one describing how you generated the data briefly?

**Comment by nvnieuwk** [comment]
Ah right, I always forget there are two readme files :grin:

**Comment by nvnieuwk** [comment]
> looks good. Cn you update the readmes? The one where all files are listed and the one describing how you generated the data briefly?

I've updated the README files

**Comment by nvnieuwk** [comment]
Thank you!

**Pull request merged**
