### PR TITLE
Added test input for openms/idxml module

### PR DESCRIPTION
**Pull request by rolivella**

### CODE REVIEW

**Comment by rolivella** [comment]
I'm not sure if I did well this PR. What I wanted to do is upload the test file `BSA_QC_file.idXML` to the folder `test-datasets/data/proteomics/parameter`.

**Comment by rolivella** [comment]
Could you please help me with this? Thanks.

**Comment by JoseEspinosa** [comment]
If this dataset is for a module as I think, then your PR should be made against the `modules` branch of the test-datasets repository. I change it, if the PR is not for a module then let me know.

**Comment by JoseEspinosa** [comment]
You have to open the PR against the `modules` branch of the test-datasets repo and you did it against the master. But I already changed it and it's OK now.
Screenshot from 2022-11-15 21-55-07

It will be great if you could modify the README to update it with the new file (this is missing) :smile:

**Comment by rolivella** [comment]
@JoseEspinosa thanks! But I'll like to understand it before modifying the README. You said that I did the PR against the `master` branch. But how it could be if I'm in the `openms_idxml branch`, as it can seen here? 

```bash
[qsample@nextflow2 test-datasets]$ git branch --verbose
  master       13c222f Merge pull request #569 from nf-core/add-citation-cff
* openms_idxml 5143cc6 Added data fro openms-idxml module
```

Thanks for your patience!

**Comment by JoseEspinosa** [comment]
No worries! The branch from which you made your PRs is not important it could be named whatever you want instead of `openms_idxml`. In the picture, I shared this will correspond to the branch name after `from`. However, the branch from the `nf-core/test-datasets` where you want to integrate the changes is the `modules`  branch (the left one in the figure). This is what I changed. In this sense, the test-datasets are a little bit of an exception since it has a branch for each of the pipelines test data and one for the modules, so for instance if you go to the `atacseq` branch (https://github.com/nf-core/test-datasets/tree/atacseq) you will see that it has a totally different content that the `modules` branch (https://github.com/nf-core/test-datasets/tree/modules).

**Pull request closed without merging**
