### PR TITLE
Add files for maxquant module

### PR DESCRIPTION
**Pull request by veitveit**

### CODE REVIEW

**Comment by grst** [comment]
Hi @veitveit, 

I don't know what happened here, but there seem to be some unrelated changes & commits.

**Comment by veitveit** [comment]
Maybe because I made the pull request to the modules branch? At least that is how I interpreted the instructions.

**Comment by grst** [comment]
> Maybe because I made the pull request to the modules branch? At least that is how I interpreted the instructions.

it could be that you started off your PR from a different branch and then try to merge into the modules branch. 
It's maybe easiest if you start from scratch with a clean copy of the modules branch and then add your modifications again. 

You can use 
```
git cherry-pick 3d2157a6025498f506f2135b1f1d343d030fb137
```
to transfer your one commit to the new branch.

**Comment by veitveit** [comment]
Thanks, did it manually in the end just before seeing your comment

**Comment by grst** [comment]
There are still a bunch of unrelated files to be deleted with this PR, though.

**Comment by veitveit** [comment]
Is this one better? If now, then I will have to start from the top

**Comment by grst** [comment]
Unfortunately, not. 

You can see the problems when looking at the `files` tab: https://github.com/nf-core/test-datasets/pull/427/files

**Pull request closed without merging**
