### PR TITLE
test file for goat/taxonsearch module

### PR DESCRIPTION
**Pull request by alxndrdiaz**
This .txt file contains the following species names and can be used as input for [goat/taxonsearch module, PR #1866](https://github.com/nf-core/modules/pull/1866): 

```
Saccharomyces cerevisiae
Arabidopsis thaliana
Caenorhabditis elegans
Drosophila melanogaster
Mus musculus
```

### CODE REVIEW

**Review by jfy133 — CHANGES_REQUESTED** [review]
This is a biological file rather than purely a generic file, so I would put this back in `delete_me`. 

If it works, you could in fact also maybe put this file with the offical NCBI taxonomy name for SARS-Cov2 in it, in the `sars-voc2` directory somewhere to make it more reusable by other tools (as this file I could easily imagine being reused)

**Comment by nvnieuwk** [comment]
> This is a biological file rather than purely a generic file, so I would put this back in `delete_me`.
> 
> If it works, you could in fact also maybe put this file with the offical NCBI taxonomy name for SARS-Cov2 in it, in the `sars-voc2` directory somewhere to make it more reusable by other tools (as this file I could easily imagine being reused)

I agree with this :)

**Comment by alxndrdiaz** [comment]
> This is a biological file rather than purely a generic file, so I would put this back in `delete_me`.
> 
> If it works, you could in fact also maybe put this file with the offical NCBI taxonomy name for SARS-Cov2 in it, in the `sars-voc2` directory somewhere to make it more reusable by other tools (as this file I could easily imagine being reused)

Done, moved the file to `data/delete_me/goat_taxonsearch/taxonomy_ids.txt`

**Comment by jfy133** [comment]
Ok, on the otherhand, I just remembered that we basically already have the same thing here: https://github.com/nf-core/test-datasets/blob/modules/data/genomics/sarscov2/genome/db/maltextract/taxon_list.txt

Why don't we consolidate these? We could replace `maltextract` with `NCBI` and extend the taxon_list.txt to have the contents of your current file? 

How does that sound?

**Comment by alxndrdiaz** [comment]
> Ok, on the otherhand, I just remembered that we basically already have the same thing here: https://github.com/nf-core/test-datasets/blob/modules/data/genomics/sarscov2/genome/db/maltextract/taxon_list.txt
> 
> Why don't we consolidate these? We could replace `maltextract` with `NCBI` and extend the taxon_list.txt to have the contents of your current file?
> 
> How does that sound?

I think it would be better to keep it as a separate file, considering that the module (goat/taxonsearch) uses [goat-cli](https://github.com/genomehubs/goat-cli) that can only query data from eukaryotic taxa in [Genomes on a Tree (GoaT)](https://goat.genomehubs.org/) database.

**Comment by jfy133** [comment]
Ok fair enough! You can merge

**Review by jfy133 — APPROVED** [review]

**Pull request merged**
