### PR TITLE
Add bacteroides_fragilis alignments

### PR DESCRIPTION
**Pull request by maxibor**
Test(1 and 2) bacteroides_fragilis fastq file aligned on bacteroides_fragilis fasta genome.

Using Bowtie2 v2.4.4 and Samtools v1.14
```bash
bowtie2-build genome.fna.gz bsubtilis
bowtie2 -x bsubtilis -1 ../fastq/test1_1.fastq.gz ../fastq/test1_2.fastq.gz > test1.sam
samtools view -b test1.sam > test1.bam
samtools sort test1.bam > test1.sorted.bam
samtools index test1.sorted.bam
bowtie2 -x bsubtilis -1 ../fastq/test2_1.fastq.gz -2 ../fastq/test2_2.fastq.gz > test2.sam
samtools view -b test2.sam > test2.bam
samtools sort test2.bam > test2.sorted.bam
samtools index test2.sorted.bam
```

### CODE REVIEW

**Comment by d4straub** [comment]
I think `tests/config/test_data.config` needs to be updated as well so that those datasets can be used? But I am by no means an expert!

**Comment by jfy133** [comment]
Looks good to me in principle, but is `-x` correct? Shouldnt it be b_fragilis?

**Comment by jfy133** [comment]
> I think `tests/config/test_data.config` needs to be updated as well so that those datasets can be used? But I am by no means an expert!

Yes but that would have to come in a modules PR, so presumably with whatever @maxibor cooking up

**Comment by maxibor** [comment]
> Looks good to me in principle, but is `-x` correct? Shouldnt it be b_fragilis?

Yes, the syntax is `bowtie2 -x index_basename -1 fwd.fq -2 rev.fq > out.sam`

**Review by jfy133 — CHANGES_REQUESTED** [review]
Please re-do with the correct BT2 build base name (as in corresponds to the species name), as bt2 stores the executed command within the BAM header, so this could be confusing if someone wanted to go in deep...

```
@PG	ID:bowtie2	PN:bowtie2	VN:2.4.4	CL:"bowtie2-align-s --wrapper basic-0 -x bsubtilis -1 test2_1.fastq.gz -2 test2_2.fastq.gz"
```

**Comment by maxibor** [comment]
Oh, I didn't even see the different species name. I guess I heard too much about _Bacillus subtilis_ recently 😆 
Fixed

```bash
bowtie2-build ../../genome/genome.fna.gz bfragilis
bowtie2 -x bfragilis -1 ../fastq/test1_1.fastq.gz -2 ../fastq/test1_2.fastq.gz > test1.sam
samtools view -b test1.sam > test1.bam
samtools sort test1.bam > test1.sorted.bam
samtools index test1.sorted.bam
bowtie2 -x bfragilis -1 ../fastq/test2_1.fastq.gz -2 ../fastq/test2_2.fastq.gz > test2.sam
samtools view -b test2.sam > test2.bam
samtools sort test2.bam > test2.sorted.bam
samtools index test2.sorted.bam
```

**Review by jfy133 — APPROVED** [review]

**Pull request merged**
