### PR TITLE
createtaxdb: add broken samplesheets

### PR DESCRIPTION
**Pull request by jfy133**

### CODE REVIEW

**Review by nvnieuwk — APPROVED** [review]
LGTM! Where will this be tested?

**Comment by jfy133** [comment]
Manually for now, but if I work out a nice way (with nf-test maybe) can add that in the future

**Comment by nvnieuwk** [comment]
Allright, I'll probably add them to the nf-schema tests themselves then if you are okay with that :p

**Comment by jfy133** [comment]
> Allright, I'll probably add them to the nf-schema tests themselves then if you are okay with that :p

Go ahead!

**Pull request merged**
