### PR TITLE
Test data for scnanoseq

### PR DESCRIPTION
**Pull request by atrull314**
Hi,

This is the commit for the minimal test dataset for the scnanoseq pipeline that was approved and in development. The pipeline is currently being validated, but wanted to get the ball rolling on some of the other required steps for pipelines.

Let me know if there are any questions

Thanks,
Austyn

### CODE REVIEW

**Comment by asp8200** [comment]
Looks okay to me, but apparently there are som conflicts that needs resolving

**Review by SPPearce — COMMENTED** [review]
Why are there a bunch of files being deleted from the testdata folder? Where did they come from, is anyone using them in a module?

**Comment by atrull314** [comment]
> Why are there a bunch of files being deleted from the testdata folder? Where did they come from, is anyone using them in a module?

It looks like its due to the timing of when we forked the repo. Testdata had been added in master and was removed after we had forked. Its not there anymore and we don't need the data that was/is there for the pipeline

**Review by SPPearce — APPROVED** [review]
Sorry, I did get the request notification last week but not at a point I was free. And then completely forgot about it.
Looks good to me.

**Pull request merged**
