### PR TITLE
taxprofiler: add a new test database including db_type

### PR DESCRIPTION
**Pull request by LilyAnderssonLee**
Add the new database test data, including the additional column `db_type`.

### CODE REVIEW

**Comment by LilyAnderssonLee** [comment]
@jfy133 @sofstam In the new database test table, `kraken2` was duplicated with three different `db_type` values. There are no special `db_params` for the long database, so the `db_params` are the same.
- short  
- long  
- both

**Review by jfy133 — COMMENTED** [review]
I think it would be good to have at least two 'long' databases (from two different tools), and some parameter within those to be slightly different - this would help with debugging.

Can be nonsense parameters, or simple things like changing kmer size or something

**Comment by LilyAnderssonLee** [comment]
Actually, updating `kraken2`/`bracken`/`centrifuge` db is not a good option. Since there is only one Nanopore sample, it could lead to issues during the process of `STANDARDISATION_PROFILES` combining reports. Therefore, I duplicated the `kaiju` and `diamond` databases instead. I'm not sure if the `db_params` are broad enough. Please proceed with your suggestions.

**Comment by LilyAnderssonLee** [comment]
It was a mistake, merging the master into the current branch. I reverted back now.

**Review by jfy133 — APPROVED** [review]
LGTM!

**Comment by jfy133** [comment]
Although thinking about it, this might be a breaking change, so might have to bump to x2 (older input sheets will not work with this version of taxprofiler)

**Pull request merged**
