### PR TITLE
Add in fastq and bam datasets with bambu/stringtie2, DESeq2, DEXSeq passing

### PR DESCRIPTION
**Pull request by yuukiiwa**
The runs [nanoseq_test-dataset_runs.txt](https://github.com/nf-core/test-datasets/files/5463323/nanoseq_test-dataset_runs.txt) for fastq inputs + bambu/stringtie2 and bam inputs + bambu/stringtie2 are attached.

### CODE REVIEW

**Comment by drpatelh** [comment]
Thanks @yuukiiwa ! Is this ready to go? So you replaced the fastq files with larger versions too? As well as adding the bam files for each sample? Just need to update the bam samplesheet to add these new files now.

**Comment by yuukiiwa** [comment]
Hi @drpatelh, thanks for the reminder! I have updated the samplesheets for fastq(nobc_nodx) and bam(nobc_nodx_noaln) and the gtf annotation and fasta reference that I used for running these fastq and bam files.

**Review by drpatelh — COMMENTED** [review]
Looks great! 😍

**Comment by yuukiiwa** [comment]
Thanks, @drpatelh!

**Pull request merged**
