### PR TITLE
add compressed GFA 1.0 files

### PR DESCRIPTION
**Pull request by heuermh**
Adding GFA 1.0 files compressed with Zstandard (zstd), GZIP, and block-compressed GZIP (BGZF).

### CODE REVIEW

**Review by JoseEspinosa — CHANGES_REQUESTED** [review]
LGTM! Although, it would be nice if you could update the README to include this files :)

**Comment by heuermh** [comment]
Sure, which README?

**Comment by JoseEspinosa** [comment]
The readme of the repository on the modules branch lists all the files available files, see here: https://github.com/nf-core/test-datasets/blob/modules/README.md

**Comment by heuermh** [comment]
Thanks!  Found it, an entry had not been added for the original uncompressed `assembly.gfa` file

**Comment by heuermh** [comment]
Needed to rebase and then force pushed

**Review by JoseEspinosa — APPROVED** [review]
Thanks @heuermh ! :rocket:

**Comment by heuermh** [comment]
Thank you, @JoseEspinosa!

**Pull request merged**
