### PR TITLE
Add taxpasta testdata

### PR DESCRIPTION
**Pull request by sofstam**
Adding test dataset for taxpasta/merge module

### CODE REVIEW

**Comment by jfy133** [comment]
Shouldn't this be going into the modules branch? And I believe (I might be wrong) that there might already be a SARS-CoV2 kraken2 report there...

**Comment by Midnighter** [comment]
There is, I've used it for the `standardise` command. See the `main.nf` in the tests here https://github.com/nf-core/modules/pull/2831/files#diff-ff43f06cfaf55f8bc77e98e7160a49dc904883e1aa65df347367980b395b85c8R11.

**Comment by sofstam** [comment]
We need  at least two profiles for testing `taxpasta/merge`, right? That is why I did added some extra examples here.

**Comment by Midnighter** [comment]
Maybe it's possible to use multiple copies with different names.

**Comment by sofstam** [comment]
Do you mean to update those lines: https://github.com/nf-core/modules/blob/master/tests/config/test_data.config#L124-L129

as 

```
 'metagenome' {
                classified_reads_assignment                    = "${params.test_data_base}/data/genomics/sarscov2/metagenome/test_1.kraken2.reads.txt"
                kraken_report                                  = "${params.test_data_base}/data/genomics/sarscov2/metagenome/test_1.kraken2.report.txt"
                kraken_report2                                =  "${params.test_data_base}/data/genomics/sarscov2/metagenome/test_1.kraken2.report.txt"
                krona_taxonomy                                 = "${params.test_data_base}/data/genomics/sarscov2/metagenome/krona_taxonomy.tab"
                seqid2taxid_map                                = "${params.test_data_base}/data/genomics/sarscov2/metagenome/seqid2taxid.map"
            }
```

**Comment by sofstam** [comment]
@jfy133 explained how I shall proceed, thank you :)

**Pull request closed without merging**
