### PR TITLE
Modules

### PR DESCRIPTION
**Pull request by ashotmarg**
These are the file for testing the hapibd nextflow module!

### CODE REVIEW

**Comment by ashotmarg** [comment]
Hi James, @jfy133, when u have time (u r probably at the hackathon now) could you review/merge this? These are just few input files for testing the [hapibd](https://github.com/browning-lab/hap-ibd) module I am working on.
Thanks,
Ashot

**Comment by jfy133** [comment]
Looks OK but what is the purpose of: `data/delete_me/hapibd/info.txt`? Do you just need an empty file? If so there are random text files in `generic` for example.

**Comment by ashotmarg** [comment]
The info.txt was just an info about those files and their purpose, but I guess it was redundant and now I've removed it.

**Review by jfy133 — APPROVED** [review]
yeah, given it's so specific and in delete_me not necessary!

**Pull request merged**
