### PR TITLE
Added csv/tsv test data

### PR DESCRIPTION
**Pull request by SusiJo**
Hi! I'd like to add tiny csv/tsv test files for new modules (e.g. csvtk/split)

Best regards,
Susanne

### CODE REVIEW

**Review by marissaDubbelaar — APPROVED** [review]
Looks good to me

**Comment by ggabernet** [comment]
Hi Susanne,

looks good to me, just could you add also a short description of the datasets in the main [readme](https://github.com/nf-core/test-datasets/tree/modules#uncategorized)

**Review by ggabernet — COMMENTED** [review]
Looking good, it'd be great to add a short description in the readme with the other datasets too though

**Comment by SusiJo** [comment]
Thanks for the comments! I've just updated the readme and added descriptions for the generic part and corrected some folder descriptions in genomics.

**Review by ggabernet — APPROVED** [review]
LGTM now!

**Pull request merged**
