### PR TITLE
Subset of HiFi reads for Arabidopsis

### PR DESCRIPTION
**Pull request by ksenia-krasheninnikova**
Input dataset to test OATK module 

https://github.com/nf-core/modules/pull/4592/

### CODE REVIEW

**Comment by ksenia-krasheninnikova** [comment]
PR for oatk module (WIP): https://github.com/nf-core/modules/pull/4592/

**Comment by SPPearce** [comment]
How large is this file? It looks like 200k lines (I'm on my mobile). Could it be smaller and still work to test the modules?

**Comment by ksenia-krasheninnikova** [comment]
Hi @SPPearce 
Thanks for having a look! I downsampled the dataset to 1.8Mb, this is as small as I could do for testing oatk. I think that should be alright given there are hosted files of a similar size.

**Comment by SPPearce** [comment]
> Hi @SPPearce Thanks for having a look! I downsampled the dataset to 1.8Mb, this is as small as I could do for testing oatk. I think that should be alright given there are hosted files of a similar size.

Great, that is a much better size now.

**Review by SPPearce — APPROVED** [review]

**Pull request merged**
