### PR TITLE
small hifi dataset for flye

### PR DESCRIPTION
**Pull request by famosab**

### CODE REVIEW

**Review by fellen31 — CHANGES_REQUESTED** [review]
Could you add this to the README? 

(perhaps name it `small_data` instead of `small-data`? Might just be personal preference, but I think most other files use _ 😄)

**Comment by famosab** [comment]
Its from here: https://www.pacb.com/connect/datasets/#AAV-datasets
I think I need to rename and properly document what is in this file. I'll re-request the review then :)

**Comment by fellen31** [comment]
> Its from here: https://www.pacb.com/connect/datasets/#AAV-datasets I think I need to rename and properly document what is in this file. I'll re-request the review then :)

Just a link to the download file and a very short description in the modules README is okay for me.

**Comment by famosab** [comment]
This is not needed anymore since we decided to skip the `--raw` tests

**Pull request closed without merging**
