### PR TITLE
added jaGalGasc40_2.pretext to test the pretextsnapshot module

### PR DESCRIPTION
**Pull request by epaule**
* it is a trimmed down version to reduce size
* it contains multiple sequences/chromosomes
* the resulting pictures will be very weak due to the low number of HiC contacts
* for testing https://github.com/nf-core/modules/issues/2576

### CODE REVIEW

**Review by muffato — COMMENTED** [review]
Can you move the file to `data/genomics/eukaryotes/galaxea_fascicularis/hic` ? and explain the directory/file in the main README.md

**Comment by epaule** [comment]
updated it based on the above

**Review by muffato — COMMENTED** [review]
There's an extra `data/genomics/` in the path :)

**Comment by epaule** [comment]
sorry, fixed it

**Pull request merged**
