### PR TITLE
Add nodes.dmp and names.dmp to folder

### PR DESCRIPTION
**Pull request by sofstam**
One of the input arguments of `kmcp profile` is:
 
```
 -X, --taxdump string      Directory of NCBI taxonomy dump files: names.dmp, nodes.dmp, optional with merged.dmp and delnodes.dmp.
```

This PR adds a folder in zipped format including `names.dmp` and `nodes.dmp`

### CODE REVIEW

**Comment by jfy133** [comment]
Maybe this should go into a kmcp folder?

**Comment by sofstam** [comment]
I thought that the folders should be always zipped but I can change to a kmcp folder instead.

**Review by jfy133 — APPROVED** [review]

**Review by jfy133 — CHANGES_REQUESTED** [review]
Ah sorry, missed your question: no you're right, if you need a folder, then yes a `tar.gz` is needed.

However what I meant is that you should have `delete_me/kmcp/kmcp.tar.gz` for example, (rather than `delete_me/kmcp.tar.gz`)

**Comment by sofstam** [comment]
Ok, I will update the PR.

**Review by jfy133 — APPROVED** [review]

**Pull request merged**
