### PR TITLE
Fix human genomics test data based on broken short-read DNA seq fastq files + adding cram files

### PR DESCRIPTION
**Pull request by FriederikeHanssen**

### CODE REVIEW

**Comment by FriederikeHanssen** [comment]
@GCJMackenzie this is great. I will pick the ones needing updating then. Would you mind maybe adding the docu to the README https://github.com/nf-core/test-datasets/blob/modules/data/genomics/homo_sapiens/README.md ? (Iam updating it in this PR, might be easiest to wait until this one is merged)

**Comment by FriederikeHanssen** [comment]
@GCJMackenzie for the data in `paired_mutect2_calls` did you use the filtered or unfiltered vcfs from sarek?

**Comment by GCJMackenzie** [comment]
Hi @FriederikeHanssen I think this should work:
    gatk GenomicsDBImport \\
        -V ../gvcf/test.genome.vcf  \\
        --genomicsdb-workspace-path test_genomicsdb \\
        -L test-datasets/data/genomics/homo_sapiens/genome/genome.interval_list

Also, as a heads up, for the the directory: /test_genomicsdb/chr22$1$40001/**__3cf81648-433d-4464-be08-23d082445c9b139814474716928_1630588248448**/
and the file:
/test_genomicsdb/chr22$1$40001/genomicsdb_meta_dir/genomicsdb_meta_**2b25a6c2-cb94-4a4a-9005-acb7c595d322**.json

The text in bold will change with each run, but the contents of the file and directory will remain the same. It would be great if we could rename the names back to what they are above as this will stop my tests for genomicsdbimport and createSomPon breaking when they try to download the files

**Comment by drpatelh** [comment]
Thanks guys!

**Pull request merged**
