### PR TITLE
Methylseq - Added simulared PE dataset

### PR DESCRIPTION
**Pull request by FelixKrueger**
10,000 PE E. coli reads with known methylation levels, non-directional to suit all possible bisulfite needs.

### CODE REVIEW

**Comment by ewels** [comment]
You're not _really_ meant to merge your own pull-requests 😉 

Whilst it's fine to have this here, the `methylseq` branch is really for the `methylseq` pipeline specifically. I think that your intention for this data is for it to be used with the new methylation DSL2 modules, in which case the data needs to be in the [`modules` branch](https://github.com/nf-core/test-datasets/tree/modules).

**Comment by FelixKrueger** [comment]
I was just reading and following the instructions ... :)

But yea, I shall add them there as well.

**Comment by FelixKrueger** [comment]
I have created a new PR, this time hopefully at the correct location: https://github.com/nf-core/test-datasets/pull/126

I'll leave the merging to another pair of eyes this time (even though "You're not *really* meant to merge your own pull-requests" doesn't sound as bad as "You're *really* not meant to merge your own pull-requests")

**Comment by ewels** [comment]
Thanks! Yes I self-merge occasionally, I figure that it’s ok as long as you realise that you’re not meant to and feel bad about it 😅

Most repositories have rules to prevent (non-admins) from doing this. But apparently not this one.

**Pull request merged**
