### PR TITLE
added transcriptome bams for riboseq

### PR DESCRIPTION
**Pull request by iraiosub**
added transcriptome bams for riboseq - required for riboWaltz module

### CODE REVIEW

**Review by pinin4fjords — CHANGES_REQUESTED** [review]
Could you update the README? You'll see the existing bams listed there.

Also, the naming of these suggests to me that they're the sorted files from the riboseq test profile run. I've actually found issues using those with e.g. Salmon, the sorting makes less sense for transcriptome BAMs (it's just what the relevant subworkflow does right now). 

Maybe it would be simpler to use the unsorted ones unless Ribowaltz needs the sorted ones?

**Comment by iraiosub** [comment]
thanks for your feedback @pinin4fjords ! I've made the requested changes. Could you please take another look and see if everything is now in order?

**Review by pinin4fjords — CHANGES_REQUESTED** [review]
Thanks for the changes! Just need to update the top-level README as well for the new files, and you're done.

**Comment by iraiosub** [comment]
done! next time will know what to change from the first go:). thanks!

**Review by pinin4fjords — APPROVED** [review]
Good work!

**Pull request merged**
