### PR TITLE
Add haplotype map reference

### PR DESCRIPTION
**Pull request by matthdsm**

### CODE REVIEW

**Review by FriederikeHanssen — COMMENTED** [review]
Would it make sense to reduce this to only have the lines for chr22/21 and rename the fato genome.fasta?

**Comment by matthdsm** [comment]
Done! I don't see why it wouldn't work

**Comment by matthdsm** [comment]
perhaps the file would be better suited under `germline_resources` instead of `genome`

**Comment by FriederikeHanssen** [comment]
yep sounds good, and a mention in the READme would also be good.

**Comment by matthdsm** [comment]
Done! Who do I bother for a merge?

**Review by JoseEspinosa — APPROVED** [review]
LGTM after applying the changes nicely suggested by @FriederikeHanssen, thanks @matthdsm :rocket:

**Pull request merged**
