### PR TITLE
Move nf-core/demultiple test data from pipeline to test-datasets

### PR DESCRIPTION
**Pull request by drpatelh**
Closes https://github.com/nf-core/demultiplex/issues/103

### CODE REVIEW

**Review by maxulysse — APPROVED** [review]

**Comment by maxulysse** [comment]
Is the samplesheet format unchanged since 1.0.0 ?

**Comment by drpatelh** [comment]
We add a new folder for 1.4.0 if required. If not, we carry on using the 1.3.0 test data until we have to change it. This at least shows you the last version in which the test data was changed.

**Comment by drpatelh** [comment]
> I think that's misleading - the data version number will be different from the pipeline version number.

Don't know of a more intelligent way to track test-data updates without making in-place changes that will break CI for older releases. Agree it's not perfect but it does the job, especially since test data isn't updated very frequently. Open to suggestions.

**Comment by drpatelh** [comment]
Also, at the moment, the samplesheets for this pipeline were all over the place:
- Within the pipeline
- Within this repo in the top-level folder as well as within `samplesheets/`

This unifies where to find all of the samplesheets in a single location.

**Comment by maxulysse** [comment]
> > Is the samplesheet format unchanged since 1.0.0 ?
> 
> Yes, they look unchanged according to commit history.

Then let's put in a `1.0.0` folder, that way, we know it's csv that works since `1.0.0`

**Comment by drpatelh** [comment]
> Yeah it's definitely an improvement. I would probably just go v1, v2, v3 etc. completely independently from the pipeline version but that's not very intuitive either.

Exactly. This way we know in which release it was last updated.

> Then let's put in a 1.0.0 folder, that way, we know it's csv that works since 1.0.0

Nope, there are other samplesheets in this new folder that were changed/added more recently in later releases. Let's start with a blank slate with `1.3.0` to indicate when everything was collated together.

**Pull request merged**
