### PR TITLE
Porepatrol test data: nanopore fastq reads

### PR DESCRIPTION
**Pull request by AnnaSyme**

### CODE REVIEW

**Comment by AnnaSyme** [comment]
Thanks @drpatelh - have made some changes and gzipped the test data.

**Comment by drpatelh** [comment]
Thanks @AnnaSyme . You can remove the `docs` directory too.

It would probably be better to report number of reads in the expected output than file sizes?

**Comment by AnnaSyme** [comment]
Yes not sure about what the best thing to report is: one step is chopping adapters, so number of reads doesn't change but total number of bases or average read length would change. I don't capture this information though -- might see if I can add to the workflow. The second filtering step can both trim and delete reads, so both number of bases and number of reads can change. Will have a look ...

**Comment by drpatelh** [comment]
👍 To be honest, Not sure how useful that information will be at this point...Maybe you can add it here when you have more realistic expectations in terms of the output?

**Comment by drpatelh** [comment]
Let me know what you think, and we can merge this.

**Comment by AnnaSyme** [comment]
I decided to add to the workflow some detail on number of reads (and number of bases) at each stage (start, after adapter trimming, and after filtering) as I think it would be useful to know (mainly if filtering has been too stringent). So I've updated the expected output here.

**Comment by drpatelh** [comment]
Thank you! Looks great 👍

**Pull request merged**
