### PR TITLE
add bowtie2

### PR DESCRIPTION
**Pull request by Joon-Klaps**
Adding bowtie2 index for testing.

### CODE REVIEW

**Review by matthdsm — COMMENTED** [review]
Shouldn't this be generated on the fly using nf-test `SETUP`?

**Review by maxulysse — DISMISSED** [review]

**Comment by maxulysse** [comment]
Actually good comment by @matthdsm

**Comment by Joon-Klaps** [comment]
> Shouldn't this be generated on the fly using nf-test `SETUP`?

It should, when its using nf-test. Unfortunately, viralrecon isn't there yet. Additionally (and the reason why I made this PR), is that viralrecon has a param `bowtie2_index` that was crashing the pipeline.

**Comment by Joon-Klaps** [comment]
Could of course also remove the (kinda redundant) param...

**Comment by matthdsm** [comment]
Not sure what the best way to go here is 🤷🏻‍♂️

**Pull request merged**
