### PR TITLE
Add test datasets for ampcombi_0.2

### PR DESCRIPTION
**Pull request by Darcy220606**
This Pr adds test datatsets that are necessary for ampcombi v. 0.2.0 submodules (parsetables/complete/cluster)

### CODE REVIEW

**Review by jasmezz — APPROVED** [review]
LGTM. Largest file is 16.3 MB, that should be fine @jfy133?

**Comment by jfy133** [comment]
That's extremely large, is it really necessary to be so big? Do all the rows need to be in there for the tests to complete successfully/

**Comment by Darcy220606** [comment]
> That's extremely large, is it really necessary to be so big? Do all the rows need to be in there for the tests to complete successfully/

I decreased it from 56 MB so in that case will decrease it more :D

**Comment by Darcy220606** [comment]
```
229.45 KB data/delete_me/ampcombi/test_files_0.2/ampir/sample_1/sample_1.ampir.tsv
227.45 KB data/delete_me/ampcombi/test_files_0.2/ampir/sample_2/sample_2.ampir.tsv
218.54 KB data/delete_me/ampcombi/test_files_0.2/amplify/sample_1/sample_1.amplify.tsv
216.25 KB data/delete_me/ampcombi/test_files_0.2/amplify/sample_2/sample_2.amplify.tsv
195.17 KB data/delete_me/ampcombi/test_gbk_0.2/sample_2.gbff
130.12 KB data/delete_me/ampcombi/test_gbk_0.2/sample_1.gbff
123.67 KB data/delete_me/ampcombi/test_faa_0.2/sample_1.faa
110.34 KB data/delete_me/ampcombi/test_faa_0.2/sample_2.faa
```

is this better @jfy133 ?

**Pull request merged**
