### PR TITLE
Add MaxQuant files

### PR DESCRIPTION
**Pull request by WackerO**
This PR adds a maxquant test dataset for a module that I am currently finishing and will PR soon

### CODE REVIEW

**Review by FriederikeHanssen — COMMENTED** [review]
would be good to add a readme to the proteomics folder, similar to genomics, to track where data comes form and how it was produced: https://github.com/nf-core/test-datasets/tree/modules/data/genomics/homo_sapiens

**Review by jfy133 — APPROVED** [review]

**Comment by jfy133** [comment]
> would be good to add a readme to the proteomics folder, similar to genomics, to track where data comes form and how it was produced: https://github.com/nf-core/test-datasets/tree/modules/data/genomics/homo_sapiens

Thats new @FriederikeHanssen ?! Has the test-data guidelines eben updated? https://nf-co.re/docs/contributing/test_data_guidelines

**Comment by FriederikeHanssen** [comment]
It has been around for a long time, at least since I added human test data probably ~March 2021, I guess it didn't got documented when this was formalized

**Comment by FriederikeHanssen** [comment]
I think it is a good idea to have given how often data there was updated, not a perfect system, but at least something, instead of "here is data, if you ever want to change anything good luck finding out what was originally done to it"

**Comment by jfy133** [comment]
Yeah absolutely! Could you make a PR to update the guidleines with your instructions :)

**Review by FriederikeHanssen — APPROVED** [review]
Awesome,. thanks a lot, Oskar!

**Comment by WackerO** [comment]
Thanks Rike and James!

**Pull request merged**
