### PR TITLE
Added test db for centrifuge

### PR DESCRIPTION
**Pull request by sofstam**
Hello,

I am working on https://github.com/nf-core/modules/issues/833 and I added a test database for centrifuge. https://github.com/nf-core/test-datasets/tree/mag/test_data

Since there is an issue with the Centrifuge database download (https://github.com/DaehwanKimLab/centrifuge/issues/231), I added the test database to the `delete_me` folder.

### CODE REVIEW

**Comment by jfy133** [comment]
I would suggest putting it in `delete_me/database`

**Review by jfy133 — APPROVED** [review]
I would suggest putting it in `delete_me/centrifuge/<file>` but otherwise theoretically I think this is an OK solution for now.

**Comment by sofstam** [comment]
Thank you for your suggestions. I accidentally created a new PR where the changes are documented there instead.

**Comment by jfy133** [comment]
OK! Approved that one too - you can merge. I will close this one.

**Pull request closed without merging**
