### PR TITLE
adding plink outputs

### PR DESCRIPTION
**Pull request by Mxrcon**
Hey, I'd like to add plink output files using the human/rnaseq vcf files. this will be very useful for the future GWAS pipeline and certainly will be used as test input for new modules!

Best regards, Davi!

### CODE REVIEW

**Review by FriederikeHanssen — CHANGES_REQUESTED** [review]
Looks good, but could you add the way you created the data here: https://github.com/nf-core/test-datasets/blob/modules/data/genomics/homo_sapiens/README.md It helps in case something has to be redone/fixed/added  in these files later down the road

**Review by FriederikeHanssen — APPROVED** [review]
👍 looks great, thanks for the addition 😊

**Comment by Mxrcon** [comment]
@FriederikeHanssen Hey, am i allowed to squash and merge now?

**Comment by FriederikeHanssen** [comment]
yes, go ahead :)

**Pull request merged**
