### PR TITLE
Add subsampled thousand genomes (HG02666) BAM file

### PR DESCRIPTION
**Pull request by JoshuaDanielRubin**
Add subsampled Thousand Genomes BAM file (ID HG02666) for use by HaploCart test

### CODE REVIEW

**Comment by JoshuaDanielRubin** [comment]
@jfy133

**Comment by jfy133** [comment]
@JoshuaDanielRubin please also update the README to describe what the file is (in the big list of things).

@maxulysse @FriederikeHanssen what do you think about adding this file speicfically to the _Homo sapiens_ section? Given the BAM file is not aligned against the same reference (presumably), maybe it should not go in there?

For reference, this file is to be used for vgan/haplocart (https://github.com/grenaud/vgan#haplocart), basically for mitochondrial haplotype assignment 

```
HaploCart performs maximum likelihood estimation to predict the mitochondrial haplogroup for reads originating from an uncontaminated modern human sample. The program also optionally provides confidence estimation of the phylogenetic placement of the sample.
```

**Comment by JoshuaDanielRubin** [comment]
I have updated the README. The reference for the added file is the GRCh38 (http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000_genomes_project/README.1000genomes.GRCh38DH.alignment). I do not know which reference is used for the other BAM files in that directory.

**Comment by FriederikeHanssen** [comment]
> @JoshuaDanielRubin please also update the README to describe what the file is (in the big list of things).
> 
> @maxulysse @FriederikeHanssen what do you think about adding this file speicfically to the _Homo sapiens_ section? Given the BAM file is not aligned against the same reference (presumably), maybe it should not go in there?
> 
> For reference, this file is to be used for vgan/haplocart (https://github.com/grenaud/vgan#haplocart), basically for mitochondrial haplotype assignment
> 
> ```
> HaploCart performs maximum likelihood estimation to predict the mitochondrial haplogroup for reads originating from an uncontaminated modern human sample. The program also optionally provides confidence estimation of the phylogenetic placement of the sample.
> ```

yeah... :( no chance to align reads against the reference we have and subsample that?

**Comment by JoshuaDanielRubin** [comment]
> > @JoshuaDanielRubin please also update the README to describe what the file is (in the big list of things).
> > @maxulysse @FriederikeHanssen what do you think about adding this file speicfically to the _Homo sapiens_ section? Given the BAM file is not aligned against the same reference (presumably), maybe it should not go in there?
> > For reference, this file is to be used for vgan/haplocart (https://github.com/grenaud/vgan#haplocart), basically for mitochondrial haplotype assignment
> > ```
> > HaploCart performs maximum likelihood estimation to predict the mitochondrial haplogroup for reads originating from an uncontaminated modern human sample. The program also optionally provides confidence estimation of the phylogenetic placement of the sample.
> > ```
> 
> yeah... :( no chance to align reads against the reference we have and subsample that?

I can do that. It looks like there are only chromosomes 21-22 in the repo so far, where can I find the full reference genome?

**Comment by jfy133** [comment]
The README might say!

---

**Comment by jfy133** [comment]
Closing in favour of https://github.com/nf-core/test-datasets/pull/638

**Pull request closed without merging**
