### PR TITLE
Add samplesheet for longread only mode in mag

### PR DESCRIPTION
**Pull request by muabnezor**

### CODE REVIEW

**Comment by jfy133** [comment]
If you proceed with this, please update the README (can make a new section that describes each samplesheet, but just list your one fdor now)

**Comment by jfy133** [comment]
@muabnezor there is an extra file in there, can you remoeve :grima

**Comment by muabnezor** [comment]
Does this look ok @jfy133 ?

**Review by jfy133 — APPROVED** [review]

**Comment by jfy133** [comment]
You can merge!

**Pull request merged**
