### PR TITLE
Add kaiju to database file

### PR DESCRIPTION
**Pull request by sofstam**

### CODE REVIEW

**Review by jfy133 — CHANGES_REQUESTED** [review]
This won't work for the test data, you need to supply a `.tar.gz` version with everything inside that we untar. This is preferred for us because then anyone who wants to  tst the pipeline and all the tools.

The reason why is we COULD add to the CI tests a download step where we download each file with `wget` and supply the directory instead. However this is not as portable as then we have to explain to a user what they have to do 'manually' to run the test profile.

I would suggest you donwload the kaiju test data that Tanja uploaded to modules, tar.gz and upload it to the taxprofiler branch instead

**Comment by sofstam** [comment]
Thank you for the comments, I will update this PR :)

**Review by jfy133 — APPROVED** [review]
Looks good - do we need the `minigut_cf` file here, as we've already got it on `modules`?

**Comment by sofstam** [comment]
I removed it :)

**Pull request merged**
