### PR TITLE
pypgx testing data 

### PR DESCRIPTION
**Pull request by Jorisvansteenbrugge**
Hi,

I added a small temporary test dataset in data/delete_me on the modules branch to test multiple new nf-core modules (e.g., https://github.com/nf-core/modules/pull/6720) for the tool PyPGx. PyPGx requires reads to be mapped to a different region than is currently represented in the human illumina bam files in the test-dataset repository. I have started a thread on Slack to discuss the best way to test this tool. However, to avoid delaying the creation of the modules, I have uploaded some temporary test data to be used in the meantime.

### CODE REVIEW

**Review by jfy133 — COMMENTED** [review]
I would suggest moving these into the homo_sapiens folder, as delete me is not sable.

Please also update the branch's README descriving how the files were generated etc.

**Comment by Jorisvansteenbrugge** [comment]
@jfy133 Thank you, I moved the data to the homo_sapiens folder, and I updated the README in that same folder. Just to be sure, is that the README you were referring to?

**Comment by jfy133** [comment]
Yes, but also in the main module README.

I don't think you need a specific `pypgx` directory though, the files can go in `genome` and `illumina` folders respecively, the formats are not specific to pypgx

**Comment by Jorisvansteenbrugge** [comment]
@jfy133 oke perfect, your comments should be addressed now!

**Review by jfy133 — APPROVED** [review]
Normally I like to also say how it was mapped (tool, version etc) but I think I've asked enough now 😬

There is something in all the places that it needs to be now

**Pull request merged**
